# Generated by Django 4.1 on 2022-10-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MuertesAccidentales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoAccidente', models.TextField(max_length=100)),
                ('numeroVictimas', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'muertesAccidentales',
            },
        ),
        migrations.CreateModel(
            name='MuertesAccidentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoVehiculo', models.TextField(max_length=100)),
                ('numeroVictimas', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'muertesAccidentes',
            },
        ),
        migrations.CreateModel(
            name='MuertesHomicidios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoHomicidio', models.TextField(max_length=100)),
                ('numeroVictimas', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'muertesHomicidios',
            },
        ),
        migrations.CreateModel(
            name='MuertesSuicidios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoSuicidio', models.TextField(max_length=100)),
                ('numeroVictimas', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'muertesSuicidios',
            },
        ),
        migrations.CreateModel(
            name='MuertesViolentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoMuerte', models.TextField(max_length=100)),
                ('numeroVictimas', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'muertesViolentas',
            },
        ),
    ]
