# Generated by Django 4.1 on 2022-08-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto_id', models.PositiveIntegerField()),
                ('nombres', models.TextField()),
                ('apellidos', models.TextField()),
                ('telefono', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=20)),
            ],
            options={
                'db_table': 'contactos',
            },
        ),
    ]
