# Generated by Django 4.1 on 2022-08-28 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_contactos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactos',
            name='contacto_id',
        ),
    ]
