# Generated by Django 4.1 on 2022-08-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_contactos', '0002_remove_contactos_contacto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='apellidos',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='nombres',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
